name: github-pages
on:
  workflow_run:
    branches: [main]
    workflows: [test]
    types: [completed]
jobs:
  main:
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          apk add mdbook
          mdbook build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: book
      - uses: actions/deploy-pages@v2
